# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff C. Bostick
email: jcbostick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experienced Scrum, Agile Coaching Professional
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://jeffbostick.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: jcbostick
github_username:  jcbostick
facebook_username: jeff.bostick
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/jcbostick/

# Address information
# address_street: 
address_city: Brooklyn
address_state: NY
address_zip: 11233

# Build settings
markdown: kramdown
